### ISSUE TITLE
Vertice mapping

### ISSUE THREAD

**Issue by tridiserkan** [hschendel/stl#5]
Hi there,

I am trying to rotate and translate triangles one by one and I came across an issue:

Initial solid has lower number of vertices than the last one. I store every vertice and its new corresponding point so that I can form a translation vector if I come across the same vertice in different triangle. 

This was basically my procedure but after translation some vertices does not match and most of the case differ with very small value but this causes an increase in number of vertices. Do you have an idea why this can be happening?

**Comment by hschendel** [comment]
This very much sounds like a numerical problem to me.
Solid.Transform basically only works because it applies exactly the same transformation on each vertex, so that for two equal vertices the results should be the same.
In general, if you transform the triangles yourself I would recommend to map the vertices to a central vertex "set", ensuring that shared vertices end up with the same entry, and then transform there.
Does that help?

**Comment by tridiserkan** [comment]
I already did the mapping. However I guess problem arises due to difference between 32 bit and 64 bit precision. I am going to try another mapping with indexes, I guess it should solve in general.
